Repository symbiote/silverstripe-gridfieldextensions, pull requests merged in 2019-03, with the labels that each got.

#287 fixed unload modal in GridFieldConfigurablePaginator
  src/GridFieldConfigurablePaginator.php
Labels: affects/v4, change/patch

#289 NEW added the ability to autopublish items that are already live
  docs/en/index.md
  src/GridFieldOrderableRows.php
Labels: affects/v4, change/minor

#290 DOCS ReadonlyField in example should be FQCN
  docs/en/index.md
Labels: affects/v4, type/docs
